get loc from path.node before it is replace
Prior to this change, when paired with the `@linaria` babel preset, it would result in the following error

```
TypeError: <root>/packages/components/src/playground/button.tsx: Cannot destructure property 'end' of 'ex.node.loc' as it is undefined.
```
source: https://github.com/callstack/linaria/issues/679#issuecomment-742125558

It seems that this loc is removed when the node is replaced and so it's being set to undefined.